- name: debconf for pma
  debconf: name=phpmyadmin question='phpmyadmin/dbconfig-install' value='true' vtype='boolean'

- name: debconf for pma
  debconf: name=phpmyadmin question='phpmyadmin/app-password-confirm' value='{{ wp_db_password }}' vtype='password'

- name: debconf for pma
  debconf: name=phpmyadmin question='phpmyadmin/mysql/admin-pass' value='{{ wp_db_password }}' vtype='password'

- name: debconf for pma
  debconf: name=phpmyadmin question='phpmyadmin/mysql/app-pass' value='{{ wp_db_password }}' vtype='password'

- name: debconf for pma
  debconf: name=phpmyadmin question='phpmyadmin/reconfigure-webserver' value='' vtype='multiselect'

- name: install pma
  apt:
    pkg: phpmyadmin
    state: latest

- name: Check if links exist
  stat:
    path: /etc/apache2/conf-enabled/apache.conf
  register: conf_exist

- name: Enable apache2.conf for PMA
  shell: |
    cd /etc/apache2/conf-enabled
    ln -s /etc/phpmyadmin/apache.conf .
  notify:
    - restart apache
  when: not conf_exist.stat.exists

- name: Change /usr/share/phpmyadmin directory permission
  file:
    path: /usr/share/phpmyadmin
    owner: site1
    group: site1
    mode: 0755
    recurse: yes

#- name: configure site
  #file: path=/var/www/phpmyadmin src=/usr/share/phpmyadmin state=link
  #notify: restart apache

